name: Kokkos Sigma Points - CMake Tests

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        build_type: [RelWithDebInfo]
        backend: [SERIAL, OPENMP]
        compiler: [g++]

    steps:
      - name: Update packages
        run: |
          sudo apt-get update
          sudo apt-get install -yq valgrind libomp-dev cmake ninja-build

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache installed dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/deps/kokkos/install
            ~/deps/catch2/install
            ~/deps/eigen/install
          key: deps-${{ matrix.backend }}-${{ matrix.compiler }}-${{ matrix.build_type }}

      - name: Build with ${{ matrix.backend }}
        run: |
          ./install.sh ${{ github.workspace }} ${{ matrix.build_type }} ${{ matrix.compiler }} ${{ matrix.backend }}

      - name: Run Unit Tests
        run: |
          cd ${{ github.workspace }}/build
          make
          ./test_sigma_points
