name: Kokkos Sigma Points - CMake Tests

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        build_type: [RelWithDebInfo]
        backend: [SERIAL, OPENMP]
        compiler: [g++]

    steps:
      - name: Update packages
        run: |
          sudo apt-get update
          sudo apt-get install -yq valgrind libomp-dev

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build with ${{ matrix.backend }}
        run: |
          ./install.sh .. ${{ matrix.build_type }} ${{ matrix.compiler }} ${{ matrix.backend }}

      - name: Run Unit Tests
        run: |
          cd ../build
          make
          ./test_sigma_points --reporter compact --success
